/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Onlineshoping;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Library {
   
    	public static void main(String args[]) {
    		ApplicationContext context =new ClassPathXmlApplicationContext("springbeans.xml");
    		User user=context.getBean("user1",User.class);
    		System.out.println(user.getBilling_address());
    		Product product=context.getBean("product1",Product.class);
    		System.out.println(product.getQuantity_in_stock());

    		    	}
        
    
}
